#!/usr/bin/env bash

# This script shows the active listening TCP and UDP ports along with the PID/Program names.

# Use `ss` to list listening ports with TCP and UDP protocols.
# Display protocol, address, port, PID, and program name
sudo ss -tulnpx

