#!/usr/bin/env bash
# this script will change your home IP address to 

# backup the hosts file
sudo cp /etc/hosts /etc/hosts.bak


# change the IP address in the hosts file
sudo sed -i '/127.0.0.1 localhost/c\127.0.02 localhost' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
