#!/usr/bin/env bash
# Script to display all active IPv4 addresses on the machine

# Use 'ip a' to list all network interfaces and filter out the IPv4 addresses
ip -4 -o addr show | awk '{print $4}' | cut -d'/' -f1

